### ISSUE TITLE
wait-for-client never terminating

### ISSUE THREAD

**Issue by TimMcCauley** [Kludex/fastapi-docker-debug#1]
Greetings @Kludex thank you for this repo. I am trying to use this with my application, however it seems that when adding `wait-for-client` it never returns, hence the application never starts. Do you know what could be going on here?

Part of my docker-compose file:

```
command: >
      sh -c "
        pip install debugpy && 
        python wait_for_localstack_ready.py &&
        python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
      "
```

Without works without any problems. 

```
command: >
      sh -c "
        python wait_for_localstack_ready.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
      "
```

It works now, I had the wrong path in `launch.json` configured, d'oh!

**Comment by Kludex** [comment]
Great! Does it work as expected now?

**Comment by TimMcCauley** [comment]
> Great! Does it work as expected now?

Yes, it does perfectly. Thanks :)
